import Link from "next/link";

import { MeasurementPrivacyControl } from "@/components/analytics/privacy-control";
import { pageMetadata } from "@/lib/seo/metadata";

export const metadata = pageMetadata("Privacy & Preferences", "How luis-ruiz.com uses inquiry details, sign-in information, browser preferences, and optional visit counts.", "/privacy");

export default function PrivacyPage() {
  return <main id="main-content" className="mx-auto grid w-full max-w-3xl gap-10 px-6 py-14 sm:py-20">
    <header><p className="eyebrow">Your information, your choices</p><h1 className="mt-4 font-display text-4xl tracking-tight sm:text-5xl">Privacy & preferences.</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">This is Luis Ruiz’s portfolio, writing space, and soundboard. Here’s what the site uses to work, and what you can turn off.</p></header>

    <section aria-labelledby="measurement-heading"><h2 id="measurement-heading" className="font-display text-2xl">Optional visit counts</h2><p className="mb-5 mt-4 leading-8 text-muted-foreground">I use simple counts to understand which public pages get attention, where project inquiries begin, and whether the soundboard gives visitors a reason to return. You can turn these counts off here. Your browser’s Do Not Track or Global Privacy Control signal also turns them off.</p><MeasurementPrivacyControl />
      <p className="mt-5 leading-8 text-muted-foreground">The report contains daily totals and public page paths. It does not contain your name, email, account ID, browsing query strings, or a persistent visitor ID. Signed-in visits and private dashboard pages are excluded. Turning measurement off does not affect contacting me, reading stories, or using the soundboard.</p>
      <p className="mt-4 leading-8 text-muted-foreground">To estimate soundboard returns, your browser remembers the date of a visit for up to 90 days of return detection. The site can then count a later-day return without sending a browser identifier. These are estimates; separate devices, cleared storage, concurrent tabs, and blocked requests affect them.</p>
      <p className="mt-4 leading-8 text-muted-foreground">When measurement is enabled, a tab can remember its last public page for 30 minutes and include that path with a project inquiry. Daily cleanup removes measurement totals outside a rolling 90-day window and temporary measurement security records older than 48 hours.</p>
    </section>

    <section aria-labelledby="inquiries-heading"><h2 id="inquiries-heading" className="font-display text-2xl">When you contact me</h2><p className="mt-4 leading-8 text-muted-foreground">The contact form sends the details you enter—your name, email, project note, and any budget or timing information—to my private inquiry inbox. I use them to respond, understand the work, and keep track of follow-ups. The form does not subscribe you to a newsletter.</p><p className="mt-4 leading-8 text-muted-foreground">Spam checks use temporary security counters and one-way keyed fingerprints to limit repeated requests. The application does not store a raw IP address with an inquiry. Inquiry records are kept separately from the 90-day visit report so I can manage our conversation and any resulting work. Please avoid including passwords or other sensitive account information.</p></section>

    <section aria-labelledby="browser-heading"><h2 id="browser-heading" className="font-display text-2xl">What stays in your browser</h2><p className="mt-4 leading-8 text-muted-foreground">Soundboard favorites, recent plays, volume, and keyboard preferences are saved in this browser. They are not synced to an account. Clearing site data removes these preferences.</p><p className="mt-4 leading-8 text-muted-foreground">Sign-in uses session cookies so protected pages can recognize an authenticated account. The owner’s writing editor also keeps local recovery copies to help recover unsaved work. These copies are specific to that browser and account; they are not a public post.</p></section>

    <section aria-labelledby="services-heading"><h2 id="services-heading" className="font-display text-2xl">Services that operate the site</h2><p className="mt-4 leading-8 text-muted-foreground">Vercel hosts the website. Supabase provides its database, sign-in, file storage, and server functions. Google handles authentication if you choose Google sign-in. Inquiry email alerts use Resend when enabled. These providers receive the information needed to deliver their services and may maintain their own operational and security logs, including network information.</p><p className="mt-4 leading-8 text-muted-foreground">Public stories, project pages, images, and sound files are available to visitors. Links to GitHub, project websites, and other external sites take you to services with their own privacy practices.</p></section>

    <section aria-labelledby="privacy-contact-heading" className="border-t border-border pt-8"><h2 id="privacy-contact-heading" className="font-display text-2xl">Questions about your information?</h2><p className="mt-4 leading-8 text-muted-foreground">Use the <Link href="/contact" className="text-primary underline underline-offset-4">contact page</Link> to ask about information you submitted or request a correction or deletion. Include enough context for me to find the conversation. Optional measurement can stay off while you send your request.</p></section>
  </main>;
}
